=== coderaiser/putout/packages/putout/lib/parse-options/validate-options/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "additionalProperties": false,
    "definitions": {
        "rule": {
            "oneOf": [{
                "description": "ğŸŠPutout rule\n\n\"off\" means rule is off\n\"on\" means it is a on\n",
                "enum": [ "on", "off"]
            }, {
                "type": "array",
                "items": [{
                    "enum": [ "on", "off"]
                }, {
                    "type": "object"
                }],
                "minItems": 2,
                "additionalItems": false
            }]
        },
        "rules": {
            "description": "ğŸŠPutout comes with a large number of rules. You can modify which rules your project uses.",
            "type": "object",
            "patternProperties": {
                "^.*$": {
                    "$ref": "#/definitions/rule"
                }
            }
        }
    },
    "properties": {
        "parser": {
            "description": "Tell ğŸŠPutout which parser to use",
            "type": "string"
        },
        "formatter": {
            "description": "Choose the way to show information about errors found",
            "type": ["string", "array"]
        },
        "processors": {
            "description": "Tell ğŸŠPutout which processors to use to support file types other then JavaScript",
            "type": "array",
            "uniqueItems": true,
            "items": {
                "type": "string"
            }
        },
        "ignore": {
            "description": "Tell ğŸŠPutout to ignore specific files and directories.",
            "type": "array",
            "uniqueItems": true,
            "items": {
                "type": "string"
            }
        },
        "match": {
            "description": "Allows to match rules for files and folders, specified by glob patterns.",
            "type": "object",
            "patternProperties": {
                "^.*$": {
                    "$ref": "#/definitions/rules"
                }
            }
        },
        "plugins": {
            "description": "Tell ğŸŠPutout which plugins to load",
            "type": "array",
            "uniqueItems": true
        },
        "rules": {"$ref": "#/definitions/rules"}
    }
}

=== coderaiser/putout/packages/operate/putout.json
{
    "parser": "babel",
    "formatter": "dump",
    "match": {
        "madrun.js": {
            "madrun/*": true
        },
        "bin": {
            "remove-process-exit": false,
            "remove-console": false
        },
        "test|.spec.js": {
            "remove-only": true,
            "remove-skip": true
        }
    },
    "ignore": [
        "node_modules",
        "fixture"
    ],
    "rules": {
        "madrun/*": false,
        "convert-esm-to-commonjs": false,
        "convert-commonjs-to-esm": false,
        "remove-only": false,
        "remove-skip": false,
        "putout": false
    },
    "plugins": [
        "apply-destructuring",
        "extract-object-properties",
        "extract-sequence-expressions",
        "madrun",
        "remove-debugger",
        "remove-only",
        "remove-skip",
        "remove-process-exit",
        "remove-console",
        "remove-empty",
        "remove-unused-variables",
        "remove-unused-private-fields",
        "remove-unused-expressions",
        "remove-useless-variables",
        "remove-constant-conditions",
        "remove-boolean-from-logical-expressions",
        "remove-nested-blocks",
        "split-variable-declarations",
        "convert-esm-to-commonjs",
        "convert-commonjs-to-esm",
        "convert-apply-to-spread",
        "convert-arguments-to-rest",
        "convert-object-assign-to-merge-spread",
        "convert-binary-expression-to-boolean",
        "convert-math-pow",
        "convert-for-each-to-for-of",
        "merge-destructuring-properties",
        "strict-mode",
        "putout"
    ]
}

=== coderaiser/putout/packages/eslint-plugin-putout/.putout.json
{
    "rules": {
        "putout": "on",
        "madrun/insert-test-dts": "on",
        "regexp/apply-starts-with": "off",
        "eslint/apply-ignores": "off",
        "eslint/add-putout": "off",
        "eslint/convert-file-to-array": "on",
        "eslint-plugin/update-ecma-version": ["on", {
            "ecmaVersion": 2025
        }]
    },
    "plugins": [
        "eslint-plugin"
    ],
    "match": {
        "eslint-fixture": {
            "esm": "off",
            "nodejs": "off",
            "nodejs/convert-commonjs-to-esm": "off",
            "apply-template-literals": "off",
            "nodejs/strict-mode": "off",
            "remove-empty": "off",
            "nodejs/remove-process-exit": "off",
            "typescript/remove-unused-types": "off",
            "remove-unused-expressions": "off",
            "arguments": "off",
            "variables/remove-useless-rename": "off",
            "variables/remove-useless-declarations": "off",
            "variables/remove-unused": "off",
            "spread": "off",
            "return/remove-useless": "off",
            "return/remove-last-empty": "off",
            "variables/remove-unreferenced": "off",
            "remove-unreachable-code": "off",
            "tape/remove-skip": "off",
            "tape/remove-only": "off",
            "remove-console": "off",
            "remove-debugger": "off",
            "typescript/remove-useless-types-from-constants": "off",
            "for-of/for": "off",
            "for-of/remove-useless": "off",
            "for-of/remove-unused-variables": "off",
            "maybe/noop": "off"
        }
    },
    "ignore": ["*.md", "eslint-fixture/.filesystem.json"]
}
